//TYPES OF USER DEFINED FUNCTIONS
//THERE ARE 4 TYPES OF USER DEFINED FUNCTIONS.
//1- NO ARGUMENT NO RETURN TYPE(NANR)
//2- NO ARGUMENT WITH RETURN TYPE(NAWR)
//3- WITH ARGUMENT NO RETURN TYPE(WANR)
//4- WITH ARGUMENT WITH RETURN TYPE(WAWR)
#include<stdio.h>
int main()
{
	return 0;
}
